### ISSUE TITLE
Cannot start: `panic: terminal entry not found`

### ISSUE THREAD

**Issue by grav** [jbszczepaniak/spotify-cli#15]
After first start, my browser opens, I authorize with Spotify, but then (and all following starts) I get this message:

```
[grav@billie spotify-cli (master)]$ ./bin/spotify-cli 
/home/grav/repo/spotify-cli/pkg/web/websocket.go:56: web player is ready, it's ID is 47570023b55cb02bc48080608102fd6c9042ea7c
/home/grav/repo/spotify-cli/pkg/player/playback.go:75: could not fetch currently playing track - fallback to None, EOF
panic: terminal entry not found

goroutine 1 [running]:
main.main()
	/home/grav/repo/spotify-cli/cmd/spotify-cli/main.go:144 +0x1153
[grav@billie spotify-cli (master)]$ ./bin/spotify-cli 
/home/grav/repo/spotify-cli/pkg/web/websocket.go:56: web player is ready, it's ID is 47570023b55cb02bc48080608102fd6c9042ea7c
/home/grav/repo/spotify-cli/pkg/player/playback.go:75: could not fetch currently playing track - fallback to None, EOF
panic: terminal entry not found

goroutine 1 [running]:
main.main()
	/home/grav/repo/spotify-cli/cmd/spotify-cli/main.go:144 +0x1153
```

Same problem on macOS catalina and Arch Linux.

**Comment by jbszczepaniak** [comment]
@grav thank you for reporting that issue - I could definitely reproduce this one. It doesn't happen all the time though 🤔 Anyways - I will look into this!

**Comment by louisjdcharles** [comment]
I am getting the same error on Arch Linux in virtualbox

**Comment by DanielWhite95** [comment]
I had the same problem, but it seems not related to the application but to the Terminal app used. I tried it on Debian and spotify-cli worked with Gnome Terminal, but didn't work with ST terminal. I think it depends on the TUI library used by the project (tui-go). See here for more details: https://github.com/marcusolsson/tui-go/issues/112
